sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.4

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit
